camel:
  cxf:
    inventory: /inventory
    hello: /hello

spring:
  profiles:
    active: mysql

soap:
  fault:
    namespace: http://schemas.xmlsoap.org/soap/envelope/

app:
  connector: BLUAGE

auth:
  jwt_token_required: true

services:
  endpoints:
    AMT:
      TrackOrder: http://localhost:8080/amt/track_order
      OrderTshirt: http://localhost:8080/amt/order_tshirt
    BLUAGE:
      TrackOrder: http://localhost:8080/bluage/track_order
      OrderTshirt: http://localhost:8080/bluage/order_tshirt