camel:
  cxf:
    inventory: /inventory
    hello: /hello

spring:
  profiles:
    active: mysql

app:
  connector: BLUAGE

services:
  endpoints:
    AMT:
      TrackOrder: http://localhost:8080/amt/track_order
      OrderTshirt: http://localhost:8080/amt/order_tshirt
    BLUAGE:
      TrackOrder: http://localhost:8080/bluage/track_order
      OrderTshirt: http://localhost:8080/bluage/order_tshirt

entitlement:
  strategy: AWS_IAM # or USER_ROLE_GROUP

environment:
  aws: local # or Actual

aws:
  iam:
    region: us-east-1
    roleArn: arn:aws:iam::123456789012:role/MyAppRole

iam:
  roleMappings:
    alice: AdminRole
    bob: ReadOnlyRole
  permissions:
    AdminRole:
      - read
      - write
      - delete
    ReadOnlyRole:
      - read
