camel:
  cxf:
    inventory: /inventory
    hello: /hello

spring:
  profiles:
    active: mysql
  config:
    import: "classpath:application-wsdl-jobs.yml"

soap:
  fault:
    namespace: http://schemas.xmlsoap.org/soap/envelope/

app:
  connector: BLUAGE

auth:
  jwt_token_required: true

services:
  endpoints:
    AMT:
      TrackOrder: http://localhost:8080/amt/track_order
      OrderTshirt: http://localhost:8080/amt/order_tshirt
    BLUAGE:
      TrackOrder: http://localhost:8080/bluage/track_order
      OrderTshirt: http://localhost:8080/bluage/order_tshirt

entitlement:
  strategy: USER_ROLE_GROUP  # or AWS_IAM

environment:
  aws: local # or Actual

aws:
  iam:
    region: us-east-1
    roleArn: arn:aws:iam::123456789012:role/MyAppRole

iam:
  roleMappings:
    alice: AdminRole
    bob: ReadOnlyRole
  permissions:
    AdminRole:
      - read
      - write
      - delete
    ReadOnlyRole:
      - read
