spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: root
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-oracle.sql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
