spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
