spring:
  datasource:
    url: jdbc:sqlite:mydb.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate.dialect: com.soaprestadapter.dialect.SQLiteDialect






