spring:
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
