spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mysql.sql
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect