CREATE TABLE tbl_generated_wsdl_classes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    wsdl_url VARCHAR2(1000) NOT NULL,
    class_data BLOB NOT NULL,
    generated_at TIMESTAMP NOT NULL
);

CREATE TABLE tbl_user (
    user_id NUMBER(19) PRIMARY KEY,
    user_name VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE tbl_role (
    role_id NUMBER(19) PRIMARY KEY,
    role_name VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE tbl_user_group (
    user_group_id NUMBER(19) PRIMARY KEY,
    role_name VARCHAR2(255 CHAR) NOT NULL,
    is_authorized NUMBER(1) NOT NULL CHECK (is_authorized IN (0, 1))
);

-- Join Table: tbl_user_role
CREATE TABLE tbl_user_role (
    user_id NUMBER(19) NOT NULL,
    role_id NUMBER(19) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES tbl_user(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES tbl_role(role_id) ON DELETE CASCADE
);

-- Join Table: tbl_role_group
CREATE TABLE tbl_role_group (
    role_id NUMBER(19) NOT NULL,
    user_group_id NUMBER(19) NOT NULL,
    PRIMARY KEY (role_id, user_group_id),
    CONSTRAINT fk_role_group_role FOREIGN KEY (role_id) REFERENCES tbl_role(role_id) ON DELETE CASCADE,
    CONSTRAINT fk_role_group_group FOREIGN KEY (user_group_id) REFERENCES tbl_user_group(user_group_id) ON DELETE CASCADE
);